heat_template_version: 2014-10-16

resources:
  userdata:
    type: OS::Heat::MultipartMime
    properties:
      parts:
      - config: {get_resource: repo_config}

  repo_config:
    type: OS::Heat::SoftwareConfig
    properties:
      config: |
        #!/bin/bash
        sleep 10
        echo "redhat" | passwd root --stdin
        # fix broken security groups
        sysctl -w net.bridge.bridge-nf-call-arptables=1
        sysctl -w net.bridge.bridge-nf-call-ip6tables=1
        sysctl -w net.bridge.bridge-nf-call-iptables=1
        sysctl -p 
outputs:
  OS::stack_id:
    value: {get_resource: userdata}
