# Enable the creation of Neutron networks for isolated Overcloud
# traffic and configure each role to assign ports (related
# to that role) on these networks.
resource_registry:
  # Network Interface templates to use (these files must exist)
  OS::TripleO::BlockStorage::Net::SoftwareConfig: /home/stack/templates/nic-configs/cinder-storage.yaml
  OS::TripleO::Compute::Net::SoftwareConfig: /home/stack/templates/nic-configs/compute.yaml
  OS::TripleO::Controller::Net::SoftwareConfig: /home/stack/templates/nic-configs/controller.yaml
  OS::TripleO::ObjectStorage::Net::SoftwareConfig: /home/stack/templates/nic-configs/swift-storage.yaml
  OS::TripleO::CephStorage::Net::SoftwareConfig: /home/stack/templates/nic-configs/ceph-storage.yaml

parameter_defaults:
  # This section is where deployment-specific configuration is done
  # Customize the IP subnets to match the local environment
  InternalApiNetCidr: 10.10.101.0/24
  StorageNetCidr: 10.10.103.0/24
  StorageMgmtNetCidr: 10.10.104.0/24
  TenantNetCidr: 10.10.102.0/24
  ExternalNetCidr: 10.10.105.0/24
  ExternalInterfaceDefaultRoute: 10.10.105.1
  # CIDR subnet mask length for provisioning network
  #ControlPlaneSubnetCidr: '24'
  # Customize the IP ranges on each network to use for static IPs and VIPs
  InternalApiAllocationPools: [{'start': '10.10.101.30', 'end': '10.10.101.250'}]
  StorageAllocationPools: [{'start': '10.10.103.30', 'end': '10.10.103.250'}]
  StorageMgmtAllocationPools: [{'start': '10.10.104.30', 'end': '10.10.104.250'}]
  TenantAllocationPools: [{'start': '10.10.102.30', 'end': '10.10.102.250'}]
  # Leave room if the external network will also be used for floating IPs
  ExternalAllocationPools: [{'start': '10.10.105.30', 'end': '10.10.105.250'}]
  # Gateway router for the provisioning network (or Undercloud IP)
  ControlPlaneDefaultRoute: 10.10.100.10
  # Generally the IP of the Undercloud
  EC2MetadataIp: 10.10.100.10
  # Define the DNS servers (maximum 2) for the overcloud nodes
  DnsServers: ["8.8.8.8","8.8.4.4"]
  # Customize the VLAN IDs to match the local environment
  InternalApiNetworkVlanID: 10
  StorageNetworkVlanID: 20
  StorageMgmtNetworkVlanID: 30
  TenantNetworkVlanID: 40
  ExternalNetworkVlanID: 50
  # Set to empty string to enable multiple external networks or VLANs
  NeutronExternalNetworkBridge: "''"
  # Customize bonding options
  NeutronNetworkVLANRanges: [50]
